apiVersion: v1
kind: Secret
metadata:
  name: {{ template "odoo.fullname" . }}
  labels:
    app: {{ template "odoo.name" . }}
    chart: {{ template "odoo.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{ if .Release.IsInstall }}
  {{ if .Values.s3.enabled }}
  aws-access-key-id: {{ randAlphaNum 16 | b64enc | quote }}
  aws-secret-access-key: {{ randAlphaNum 16 | b64enc | quote }}
  {{ end }}
  {{ if .Values.azure.enabled }}
  azure-storage-account-url: {{ randAlphaNum 16 | b64enc | quote }}
  azure-storage-connection-string: {{ randAlphaNum 16 | b64enc | quote }}
  {{ end }}
  odoo-admin-passwd: {{ randAlphaNum 16 | b64enc | quote }}
  odoo-admin-user-password: {{ randAlphaNum 16 | b64enc | quote }}
  odoo-smtp-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{ else }}
  {{ if .Values.s3.enabled }}
  aws-access-key-id: {{ index (lookup "v1" "Secret" .Release.Namespace (include "odoo.fullname" . )).data "aws-access-key-id" }}
  aws-secret-access-key: {{ index (lookup "v1" "Secret" .Release.Namespace (include "odoo.fullname" . )).data "aws-secret-access-key" }}
  {{ end }}
  {{ if .Values.azure.enabled }}
  azure-storage-account-url: {{ index (lookup "v1" "Secret" .Release.Namespace (include "odoo.fullname" . )).data "azure-storage-account-url" }}
  azure-storage-connection-string: {{ index (lookup "v1" "Secret" .Release.Namespace (include "odoo.fullname" . )).data "azure-storage-connection-string" }}
  {{ end }}
  odoo-admin-passwd: {{ index (lookup "v1" "Secret" .Release.Namespace (include "odoo.fullname" . )).data "odoo-admin-passwd" }}
  odoo-admin-user-password: {{ index (lookup "v1" "Secret" .Release.Namespace (include "odoo.fullname" . )).data "odoo-admin-user-password" }}
  odoo-smtp-password: {{ index (lookup "v1" "Secret" .Release.Namespace (include "odoo.fullname" . )).data "odoo-smtp-password" }}
  {{ end }}
---
{{- if not .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "externaldb"  }}
  labels:
    app: {{ printf "%s-%s" .Release.Name "externaldb"  }}
    chart: {{ template "odoo.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{ if .Release.IsInstall }}
  db-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{ else }}
  db-password: {{ index (lookup "v1" "Secret" .Release.Namespace (printf "%s-%s" .Release.Name "externaldb" )).data "db-password" }}
  {{ end }}
{{- end }}
---
{{ if .Values.backup.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: backup-credentials
  labels:
    app: {{ template "odoo.name" . }}
    chart: {{ template "odoo.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
{{ if .Release.IsInstall }}
  {{ if or (eq .Values.backup.platform "aws") (eq .Values.backup.platform "do") }}
  aws-access-key-id: {{ randAlphaNum 16 | b64enc | quote }}
  aws-secret-access-key: {{ randAlphaNum 16 | b64enc | quote }}
  {{ end }}
  {{ if eq .Values.backup.platform "azure" }}
  azure-storage-account-url: {{ randAlphaNum 16 | b64enc | quote }}
  {{ end }}
{{ else }}
  {{ if or (eq .Values.backup.platform "aws") (eq .Values.backup.platform "do") }}
  aws-access-key-id: {{ index (lookup "v1" "Secret" .Release.Namespace "backup-credentials").data "aws-access-key-id" }}
  aws-secret-access-key: {{ index (lookup "v1" "Secret" .Release.Namespace "backup-credentials").data "aws-secret-access-key" }}
  {{ end }}
  {{ if eq .Values.backup.platform "azure" }}
  azure-storage-account-url: {{ index (lookup "v1" "Secret" .Release.Namespace "backup-credentials").data "azure-storage-account-url" }}
  {{ end }}
{{ end }}
{{ end }}
---
{{ if .Values.remote.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: remote-credentials
  labels:
    app: {{ template "odoo.name" . }}
    chart: {{ template "odoo.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
{{ if .Release.IsInstall }}
  {{ if or (eq .Values.remote.platform "aws") (eq .Values.remote.platform "do") }}
  aws-access-key-id: {{ randAlphaNum 16 | b64enc | quote }}
  aws-secret-access-key: {{ randAlphaNum 16 | b64enc | quote }}
  {{ end }}
  {{ if eq .Values.remote.platform "azure" }}
  azure-storage-account-url: {{ randAlphaNum 16 | b64enc | quote }}
  {{ end }}
{{ else }}
  {{ if or (eq .Values.remote.platform "aws") (eq .Values.remote.platform "do") }}
  aws-access-key-id: {{ index (lookup "v1" "Secret" .Release.Namespace "remote-credentials").data "aws-access-key-id" }}
  aws-secret-access-key: {{ index (lookup "v1" "Secret" .Release.Namespace "remote-credentials").data "aws-secret-access-key" }}
  {{ end }}
  {{ if eq .Values.remote.platform "azure" }}
  azure-storage-account-url: {{ index (lookup "v1" "Secret" .Release.Namespace "remote-credentials").data "azure-storage-account-url" }}
  {{ end }}
{{ end }}
{{ end }}
