apiVersion: v1
kind: Secret
metadata:
  name: {{ template "odoo.fullname" . }}
  labels:
    app: {{ template "odoo.name" . }}
    chart: {{ template "odoo.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{ if .Release.IsInstall }}
  {{ if .Values.s3.enabled }}
  aws-access-key-id: {{ randAlphaNum 16 | b64enc | quote }}
  aws-secret-access-key: {{ randAlphaNum 16 | b64enc | quote }}
  {{ end }}
  odoo-admin-passwd: {{ randAlphaNum 16 | b64enc | quote }}
  odoo-admin-user-password: {{ randAlphaNum 16 | b64enc | quote }}
  odoo-smtp-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{ else }}
  {{ if .Values.s3.enabled }}
  aws-access-key-id: {{ index (lookup "v1" "Secret" .Release.Namespace (include "odoo.fullname" . )).data "aws-access-key-id" }}
  aws-secret-access-key: {{ index (lookup "v1" "Secret" .Release.Namespace (include "odoo.fullname" . )).data "aws-secret-access-key" }}
  {{ end }}
  odoo-admin-passwd: {{ index (lookup "v1" "Secret" .Release.Namespace (include "odoo.fullname" . )).data "odoo-admin-passwd" }}
  odoo-admin-user-password: {{ index (lookup "v1" "Secret" .Release.Namespace (include "odoo.fullname" . )).data "odoo-admin-user-password" }}
  odoo-smtp-password: {{ index (lookup "v1" "Secret" .Release.Namespace (include "odoo.fullname" . )).data "odoo-smtp-password" }}
  {{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ print .Values.name "-github-webhook" | quote }}
  labels:
    app: {{ template "odoo.name" . }}
    chart: {{ template "odoo.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  WebHookSecretKey: {{ randAlphaNum 10 | b64enc | quote }}
---
{{- if not .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "externaldb"  }}
  labels:
    app: {{ printf "%s-%s" .Release.Name "externaldb"  }}
    chart: {{ template "odoo.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{ if .Release.IsInstall }}
  db-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{ else }}
  db-password: {{ index (lookup "v1" "Secret" .Release.Name (printf "%s-%s" .Release.Name "externaldb")).data "db-password" }}
  {{ end }}
{{- end }}
