# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.0
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: false
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: true
odoo_version: 16.0
org_name: Open Source Integrators
org_slug: opensourceintegrators
rebel_module_groups: []
repo_description: 'TODO: add repo description'
repo_name: My Project Name
repo_slug: my-repo-slug
repo_website: https://github.com/opensourceintegrators/my-repo-slug
travis_apt_packages: []
travis_apt_sources: []

