## Database external to the cluster
externalDatabase:
#  host: odoo-template-dev.db.example.com
#  user: doadmin
#  port: 25060
#  defaultdb: defaultdb

## Database in the cluster
postgresql:
  enabled: true
  postgresqlUsername: odoo
  defaultdb: postgres
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 2Gi

service:
  type: LoadBalancer
  externalTrafficPolicy: Cluster

build:
  enabled: false
#  source_repository_url: https://github.com/ursais/odoo-template.git
#  source_repository_ref: 14.0
#  context_dir: odoo

persistence:
  enabled: false
#  storageClass: nfs
#  accessMode: ReadWriteMany
#  size: 4Gi

azure:
  enabled: false

s3:
  enabled: false
#  aws_host: odoo-template.sfo3.digitaloceanspaces.com
#  aws_region: sfo3

redis:
  enabled: false
#  host: odoo-redis-master
#  port: 6379
#  prefix: odoo-template-dev
#  expiration: 604800
#  expiration_anonymous: 10800
#  copy_existing_fs_sessions: 0
#  purge_existing_fs_sessions: 1
#  cluster:
#    enabled: false
#  master:
#    persistence:
#      storageClass: nfs
#      size: 2Gi

mailhog:
  enabled: true

postfix:
  enabled: false

smtp:
  enabled: true
  ssl: false
  user: false

marabunta:
  allow_serie: true
  mode: base

resources:
  limits:
    cpu: "1"
    memory: 2Gi
  requests:
    cpu: 300m
    memory: 512Mi

livenessProbe:
  enabled: true
  initialDelaySeconds: 600
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

affinity: {}

name: odoo
fullname: "Odoo Template Dev"
project: odoo-template
environment: dev
platform: aws, azure or do
distribution: kubernetes or openshift
application_domain: odoo-template.apps.cluster.example.com
timezone: America/Phoenix
image: docker.pkg.github.com/ursais/odoo-template/odoo-template:latest
odooUsername: admin
odooEmail: support@example.com
odooListDB: true
